### ISSUE TITLE
Issues with geography types on SQL Azure

### ISSUE THREAD

**Issue by boettr** [jonwagner/Insight.Database#214]
When querying * from a table that includes a geography column insight fails with a null reference.

If I exclude the column from the select the query executes without error. I am not attempting to map the column back to a property.

Curiously enough it appears to work fine one SQL 2012 that I have installed locally.

Stack trace seems to indicate that it is failing on column.Type.GetHashCode();

   at Insight.Database.CodeGenerator.SchemaIdentity..ctor(IDataReader reader) in c:\projects.net\Insight\Insight.Database\Insight.Database\CodeGenerator\SchemaIdentity.cs:line 73
   at Insight.Database.CodeGenerator.DbReaderDeserializer.GetDeserializer(IDataReader reader, Type type, IRecordStructure structure, SchemaMappingType mappingType) in c:\projects.net\Insight\Insight.Database\Insight.Database\CodeGenerator\DbReaderDeserializer.cs:line 169
   at Insight.Database.CodeGenerator.DbReaderDeserializer.GetDeserializer[T](IDataReader reader, IRecordStructure structure) in c:\projects.net\Insight\Insight.Database\Insight.Database\CodeGenerator\DbReaderDeserializer.cs:line 104
   at Insight.Database.OneToOne`1.GetRecordReader(IDataReader reader) in c:\projects.net\Insight\Insight.Database\Insight.Database\Structure\OneToOne.cs:line 197
   at Insight.Database.DBReaderExtensions.<AsEnumerable>d__0`1.MoveNext() in c:\projects.net\Insight\Insight.Database\Insight.Database\Extensions\DbReaderExtensions.cs:line 75
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Insight.Database.DBReaderExtensions.ToList[T](IDataReader reader, IRecordReader`1 recordReader) in c:\projects.net\Insight\Insight.Database\Insight.Database\Extensions\DbReaderExtensions.cs:line 38
   at Insight.Database.Structure.ChildRecordReader`3.Insight.Database.Structure.IChildRecordReader<TResult,TId>.Read(IDataReader reader) in c:\projects.net\Insight\Insight.Database\Insight.Database\Structure\ChildRecordReader.cs:line 43
   at Insight.Database.Structure.Children`3.Read(IEnumerable`1 parents, IDataReader reader) in c:\projects.net\Insight\Insight.Database\Insight.Database\Structure\Children.cs:line 70
   at Insight.Database.Structure.QueryReader`1.ReadChildren(IDataReader reader, IEnumerable`1 results) in c:\projects.net\Insight\Insight.Database\Insight.Database\Structure\QueryReader.cs:line 67
   at Insight.Database.Structure.ListReader`1.Read(IDbCommand command, IDataReader reader) in c:\projects.net\Insight\Insight.Database\Insight.Database\Structure\ListReader.cs:line 58
   at Insight.Database.DBConnectionExtensions.<>c__DisplayClass69`1.<Query>b__68(IDbCommand cmd, IDataReader r) in c:\projects.net\Insight\Insight.Database\Insight.Database\Extensions\DBConnectionExtensions.cs:line 501
   at Insight.Database.DBConnectionExtensions.ExecuteAndAutoClose[T](IDbConnection connection, Func`2 getCommand, Func`3 translate, CommandBehavior commandBehavior) in c:\projects.net\Insight\Insight.Database\Insight.Database\Extensions\DBConnectionExtensions.cs:line 1461
   at Insight.Database.DBConnectionExtensions.Query[T](IDbConnection connection, String sql, Object parameters, IQueryReader`1 returns, CommandType commandType, CommandBehavior commandBehavior, Nullable`1 commandTimeout, IDbTransaction transaction, Object outputParameters) in c:\projects.net\Insight\Insight.Database\Insight.Database\Extensions\DBConnectionExtensions.cs:line 497

**Comment by jonwagner** [comment]
Insight caches plans based upon all of the columns that are returned, so excluding it would make the problem go away.

custom sql types are a little weird in .net. if it's working off 2012 but not a different version of sql, it might be that the server is returning a 2014 geography, but you don't have the supporting types loaded.

I don't have my windows machine with me to look up the details, but I would start there first.

**Comment by jonwagner** [comment]
I don't see anything out of the ordinary in the code. If you post a case to reproduce the problem, I can look into it.

**Comment by boettr** [comment]
I agree the code looks fine.

I tried attaching the same code which threw the error in azure to a local box and attached it to the same sql azure database and the code executed just fine. 

The only circumstance that I can reproduce the behaviour is by running a from an azure web app so it must be something specific to those machines.

Happy for you to close this given the very limited scope that it appears to affect.

**Comment by jonwagner** [comment]
Alright - if it comes up again, let's try to capture a little more information and maybe we track it down then.
