### ISSUE TITLE
I'm getting "Operation could destabilize the runtime"

### ISSUE THREAD

**Issue by uzigula** [jonwagner/Insight.Database#325]
I have this query :
``` csharp
var results = db.Query("dbo.ContactSearch", parameters, Query.Returns<Contact>()
.ThenChildren(Some<Address>.Records, id: a => a.ContactId.Value, into: (c, a) => c.Addresses = a.ToArray().AddPrimaryIfNotExists())
.ThenChildren(Some<PhoneNumber>.Records, id: a => a.ContactId.Value, into: (c, p) => .PhoneNumbers = p.ToArray())
.ThenChildren(Some<EmailAddress>.Records, id: a => a.ContactId.Value, into: (c, e) => c.EmailAddresses = e.ToArray())
.ThenChildren(Some<Tag>.Records, id: a => a.ContactId.Value, into: (c, t) => c.Tags = t.ToArray())
.ThenChildren(Some<ListContact>.Records, id: a => a.ContactId.Value, into: (c, a) => c.Lists = a.ToList()));
```

I had this with version 4.2.5 which this was working well
But when i update to 5.2.8, start firing "Operation could destabilize the runtime"

the classes are the following:
``` 
	public class Contact : DetailRecord
	{

        #endregion
        public int ContactTypeId { get; set; }
        public int? ContactId { get; set; }
        public int? ProjectId { get; set; }
		public string ContactName { get; set; }
		public string CompanyName { get; set; }
		public string SearchName { get; set; }
		public string SortName { get; set; }
		public string Attention { get; set; }
		public Address[] Addresses { get; set; }
		public PhoneNumber[] PhoneNumbers { get; set; }
		public EmailAddress[] EmailAddresses { get; set; }
        public Tag[] Tags { get; set; }
        public string CounselTo { get; set; }
        public bool AddressCounselTo { get; set; }
        public string Comments { get; set; }

        public string Notes { get; set; }
		public string PreferredContactType { get; set; }
        public bool Company { get; set; }
        public string TaxId { get; set; }
        public int? GroupNumber { get; set; }
        public bool Redacted { get; set; }
        public bool RedactedSkip { get; set; }
        public string RedactedName { get; set; }
        public string OvernightName { get; set; }
        public string RedactedComments { get; set; }
        public bool IsMSLContact { get; set; }
        public bool IsDebtor { get; set; }
        public int? ImportContactId { get; set; }
        public bool CreditorMatrix { get; set; }
        public IEnumerable<ListContact> Lists { get; set; } 
		public PhoneNumber[] PhoneByType(string type)
		{
			if (PhoneNumbers == null)
				return new PhoneNumber[] { };
			return PhoneNumbers.Where(p => p.PhoneType.Equals(type, StringComparison.CurrentCultureIgnoreCase))
				.ToArray();
		}

	    public Address[] AddressByType(string type)
	    {
	        if(Addresses == null)
                return new Address[] {};
	        return Addresses.Where(p => p.AddressType != null).Where(p => p.AddressType.Equals(type, StringComparison.CurrentCultureIgnoreCase)).ToArray();
	    }

        public RT GetProperty<T, RT>(Func<T, RT> action, string type = ContactType.Default)
		{
			var source = GetSource<T>(type);
			if (source == null)
				return default(RT);
			return action.Invoke(source);
		}
		public void SetProperty<T>(Action<T> action, string type = ContactType.Default)
		{
			var source = GetSource<T>(type);
			if (source == null)
				return;
			action.Invoke(source);
		}
		public RT GetProperty<T, RT>(Func<T, RT> action, Func<T, bool> where)
		{
			var source = GetSource<T>(where);
			if (source == null)
				return default(RT);
			return action.Invoke(source);
		}
		public void SetProperty<T>(Action<T> action, Func<T, bool> where)
		{
			var source = GetSource<T>(where);
			if (source == null)
				return;
			action.Invoke(source);
		}
		private T GetSource<T>(string type = ContactType.Default)
		{
			T source = default(T);
			if (typeof(Address).IsAssignableFrom(typeof(T)))
				source = Addresses.Where(x => x.ContactType.Equals(type, StringComparison.CurrentCultureIgnoreCase))
					.FirstOrDefault()
					.ConvertTo<T>();
			else if (typeof(PhoneNumber).IsAssignableFrom(typeof(T)))
				source = PhoneNumbers.Where(x => x.ContactType.Equals(type, StringComparison.CurrentCultureIgnoreCase))
					.FirstOrDefault()
					.ConvertTo<T>();
			else if (typeof(EmailAddress).IsAssignableFrom(typeof(T)))
				source = EmailAddresses.Where(x => x.ContactType.Equals(type, StringComparison.CurrentCultureIgnoreCase))
					.FirstOrDefault()
					.ConvertTo<T>();
			return source;
		}
		private T GetSource<T>(Func<T, bool> where)
		{
			T source = default(T);
			if (typeof(Address).IsAssignableFrom(typeof(T)))
			{
				var predicate = where as Func<Address, bool>;
				source = Addresses.Where(predicate).FirstOrDefault().ConvertTo<T>();
			}
			else if (typeof(PhoneNumber).IsAssignableFrom(typeof(T)))
			{
				var predicate = where as Func<PhoneNumber, bool>;
				source = PhoneNumbers.Where(predicate).FirstOrDefault().ConvertTo<T>();
			}
			else if (typeof(EmailAddress).IsAssignableFrom(typeof(T)))
			{
				var predicate = where as Func<EmailAddress, bool>;
				source = EmailAddresses.Where(predicate).FirstOrDefault().ConvertTo<T>();
			}
			return source;
		}
	}
```

this is the stack trace

```
   at Get-CaseManagement.Data.Address-ContactId-dc70810c-c44e-4736-9270-f5e31256c879(Address )
   at System.Linq.Lookup`2.Create[TSource](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at System.Linq.GroupedEnumerable`3.GetEnumerator()
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector)
   at Insight.Database.Structure.ChildMapper`3.MapChildren(IEnumerable`1 roots, IEnumerable`1 children) in c:\projects.net\Insight.Database\Insight.Database\Structure\ChildMapper.cs:line 77
   at Insight.Database.Structure.Children`3.Read(IEnumerable`1 parents, IDataReader reader) in c:\projects.net\Insight.Database\Insight.Database\Structure\Children.cs:line 70
   at Insight.Database.Structure.QueryReader`1.ReadChildren(IDataReader reader, IEnumerable`1 results) in c:\projects.net\Insight.Database\Insight.Database\Structure\QueryReader.cs:line 67
   at Insight.Database.Structure.ListReader`1.Read(IDbCommand command, IDataReader reader) in c:\projects.net\Insight.Database\Insight.Database\Structure\ListReader.cs:line 58
   at Insight.Database.DBCommandExtensions.<>c__DisplayClass2`1.<Query>b__1(IDbCommand cmd, IDataReader r) in c:\projects.net\Insight.Database\Insight.Database\Extensions\DBCommandExtensions.cs:line 153
   at Insight.Database.DBConnectionExtensions.ExecuteAndAutoClose[T](IDbConnection connection, Func`2 getCommand, Func`3 translate, CommandBehavior commandBehavior) in c:\projects.net\Insight.Database\Insight.Database\Extensions\DBConnectionExtensions.cs:line 1461
   at Insight.Database.DBCommandExtensions.Query[T](IDbCommand command, IQueryReader`1 returns, CommandBehavior commandBehavior, Object outputParameters) in c:\projects.net\Insight.Database\Insight.Database\Extensions\DBCommandExtensions.cs:line 149
   at CaseManagement.Data.SQL.ConnectionExtensions.Query[T](Database db, String sql, Object parameters, IQueryReader`1 reader, Object[] additionalParameters) in C:\code\CaseManagement\Data\CaseManagement.Data.SQL\ConnectionExtensions.cs:line 39
   at CaseManagement.Data.SQL.Directory.ContactRepository.Get(ContactCriteria criteria) in C:\code\CaseManagement\Data\CaseManagement.Data.SQL\Directory\ContactRepository.cs:line 29
   at CaseManagement.Data.Project.ClaimService.AddCreditorContactToSearchResults(List`1 searchResults) in C:\code\CaseManagement\Data\CaseManagement.Data\Project\Claim\ClaimService.cs:line 1473
   at CaseManagement.Data.Project.ClaimService.Search(IClaimSearchCriteria criteria) in C:\code\CaseManagement\Data\CaseManagement.Data\Project\Claim\ClaimService.cs:line 66
   at CaseManagement.Web.Controllers.ClaimController.Search(ClaimSearchCriteriaModel criteria) in C:\code\CaseManagement\Web\CaseManagement.Web\Controllers\ClaimController.cs:line 56
```

**Comment by jonwagner** [comment]
We should be able to track that down. From the stack trace, it looks like the issue is in reading the ContactID from the Address class.

Let's see if we can get a smaller repro case:

1. Does the error still occur if you just do the Contact/Address relationship? i.e. if you chop off the last 4 ThenChildren clauses, does it still fail?
2. Can you include the Address class in the repro case?

**Comment by kevinsea** [comment]
I saw the .Net 2.0 preview 2 was published, I haven't downloaded it yet, but it appears to be a step forward.  
http://sdtimes.com/net-core-2-0-preview/ .  I would think ODBC would be part of this update.

FWIW, AWS continues to add support for Core: https://adtmag.com/articles/2017/07/12/aws-net-core.aspx

**Comment by jonwagner** [comment]
Closing this due to inactivity. If you can put together a smaller repro case, we can reopen it and fix it.
