### ISSUE TITLE
Bulkload for PostGreSQL null reference on .net core

### ISSUE THREAD

**Issue by jbright** [jonwagner/Insight.Database#342]
I tried to get a unit test so that I could create a PR but I had a package issue when cloning and running on my mac. (Could be my issue  on my development environment). I wanted to try to find the exact line of code that is causing the issue. I was able to reproduce this issue with this code snippet. The only packages needed are:

```
dotnet add package Insight.Database --version 6.1.0
dotnet add package Insight.Database.Providers.PostgreSQL --version 6.1.0
dotnet add package Npgsql
```

The code:

```cs
using System;
using System.Collections.Generic;
using Insight.Database;
using Insight.Database.Providers.PostgreSQL;
using Npgsql;

namespace TestBulkLoad
{
    public class User
    {
        public string first_name { get; set; }    
        public string last_name { get; set; }
        public string email { get; set; }
    }

    class Program
    {
        static void Main(string[] args)
        {
            var data = new List<User>()
            {
                new User() { email = "john@dough.com", first_name = "John", last_name = "Dough"},
                new User() { email = "jane@dough.com", first_name = "Jane", last_name = "Dough"}
            };

            PostgreSQLInsightDbProvider.RegisterProvider();
            var database = new NpgsqlConnectionStringBuilder("Host=localhost; Port=PORT#; Database=DATABASE; User ID=postgres; Pwd=Password1;").Connection();

            database.ExecuteSql(@"CREATE TABLE test_tmp (
                id SERIAL PRIMARY KEY,
                first_name varchar(70) DEFAULT NULL,
                last_name varchar(100) DEFAULT NULL,
                email varchar(255) DEFAULT NULL
            );");

            database.BulkCopy("test_tmp", data);
        }
    }
}
```

The result of `dotnet run` is

```
Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at Insight.Database.Providers.PostgreSQL.PostgreSQLInsightDbProvider.BulkCopy(IDbConnection connection, String tableName, IDataReader reader, Action`1 configure, InsightBulkCopyOptions options, IDbTransaction transaction)
   at Insight.Database.DBConnectionExtensions.<>c__DisplayClass198_0.<BulkCopy>b__0(IDbConnection c)
   at Insight.Database.DBConnectionExtensions.ExecuteAndAutoClose[T](IDbConnection connection, Func`2 action, Boolean closeConnection)
   at Insight.Database.DBConnectionExtensions.BulkCopy[T](IDbConnection connection, String tableName, IEnumerable`1 list, Action`1 configure, Boolean closeConnection, InsightBulkCopyOptions options, IDbTransaction transaction)
   at TestBulkLoad.Program.Main(String[] args) in /Users/jbright/dev/23bits/HelloWorld/TestBulkLoad/Program.cs:line 36
```

**Comment by jonwagner** [comment]
Added a test case that matches yours. Passes on windows & osx:

https://github.com/jonwagner/Insight.Database/commit/10d9376dbfbdeb6bc6026545fc7ff973cd8a985c

**Comment by jbright** [comment]
Hmm. I updated my database connection so that I didn't specify a port. The new error is:

```
Npgsql.PostgresException: 22P04: unterminated CSV quoted field
```

**Comment by anirbanbh** [comment]
Facing same problem as well.

**Comment by jbright** [comment]
@anirbanbh are you loading data into a AWS RDS PG database? IIRC that's where I was facing the issue. I was **not** able to work around it.

**Comment by jonwagner** [comment]
I'm happy to fix anything I can reproduce, so if you can post some code that reproduces the problem, we can reopen this.
