### ISSUE TITLE
Error SqlNullValueException: Data is Null after change target framework from NET462 to netcoreapp2

### ISSUE THREAD

**Issue by madrianr** [jonwagner/Insight.Database#359]
## Type
What kind of issue is this?

```
[x ] Bug report.
[ ] Feature request.
```
## Current Behavior
after change target framework from NET462 to netcoreapp2 I get an error:
System.Data.SqlTypes.SqlNullValueException: Data is Null. This method or property cannot be called on Null values.

this happens only on target Framework netcoreapp2 not NET462...
![unbenannt](https://user-images.githubusercontent.com/10518186/36728119-97611c56-1bb7-11e8-8b03-69d0d6445cf6.JPG)

here the error message in Detail:
System.Data.SqlTypes.SqlNullValueException: Data is Null. This method or property cannot be called on Null values.
   at System.Data.SqlClient.SqlBuffer.get_String()
   at Insight.Database.Providers.Default.SqlParameterHelper.CreateParameter(SqlDataReader reader, ParameterColumnMap columnMap)
   at Insight.Database.Providers.Default.SqlParameterHelper.DeriveParameters(SqlCommand cmdToPopulate)
   at Insight.Database.SqlInsightDbProvider.DeriveParametersFromStoredProcedure(IDbCommand command)
   at Insight.Database.Providers.InsightDbProvider.<>c__DisplayClass12_0.<DeriveParameters>b__0(IDbConnection _)
   at Insight.Database.DBConnectionExtensions.ExecuteAndAutoClose[T](IDbConnection connection, Func`2 getCommand, Func`3 translate, CommandBehavior commandBehavior)
   at Insight.Database.Providers.InsightDbProvider.DeriveParameters(IDbCommand command)
   at Insight.Database.CodeGenerator.DbParameterGenerator.CreateClassInputParameterGenerator(IDbCommand command, Type type)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Insight.Database.DBCommandExtensions.AddParameters(IDbCommand cmd, Object parameters)
   at Insight.Database.DBConnectionExtensions.CreateCommand(IDbConnection connection, String sql, Object parameters, CommandType commandType, Nullable`1 commandTimeout, IDbTransaction transaction)
   at Insight.Database.DBConnectionExtensions.<>c__DisplayClass167_0`1.<Query>b__0(IDbConnection c)
   at Insight.Database.DBConnectionExtensions.ExecuteAndAutoClose[T](IDbConnection connection, Func`2 getCommand, Func`3 translate, CommandBehavior commandBehavior)
   at Insight.Database.DBConnectionExtensions.Query[T](IDbConnection connection, String sql, Object parameters, IQueryReader`1 returns, CommandType commandType, CommandBehavior commandBehavior, Nullable`1 commandTimeout, IDbTransaction transaction, Object outputParameters)
   at Insight.Database.DBConnectionExtensions.Query[T1](IDbConnection connection, String sql, Object parameters, CommandType commandType, CommandBehavior commandBehavior, Nullable`1 commandTimeout, IDbTransaction transaction, Object outputParameters)
   at Gpdb.Helpers.SqlDatabase.SPSelect[T](HttpContext context, IDbConnection db, String sql, Object parameters) in D:\Entwicklung\temp\GPDB\src\GPDB\Helpers\DatabaseHelpers.cs:line 24
   at Gpdb.Areas.Abfragesystem.Controllers.HomeController.Index(Nullable`1 id, String quid) in D:\Entwicklung\temp\GPDB\src\GPDB\Areas\Abfragesystem\Controllers\HomeController.cs:line 90
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionMethodAsync>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextActionFilterAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResourceFilter>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeFilterPipelineAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Session.SessionMiddleware.<Invoke>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Session.SessionMiddleware.<Invoke>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>d__7.MoveNext()

see also picture

## Expected behavior

Complete as needed

## Steps to Reproduce

Complete as needed

### Any other comment

(n/a)

**Comment by Jaxelr** [comment]
Could you provide a sample code snippet that generates the error? Also if you could add the SQL used (SQL Server, or any other version)

**Comment by madrianr** [comment]
give me some time to prepare such a test Project - I'm very busy in the Moment...

**Comment by jonwagner** [comment]
I updated some parameter reading code to make it safer to read null parameters. That should fix any issues with null references there.

This will be in v6.2 next week. If it's still an issue after that, please post more repro steps and reopen.
