### ISSUE TITLE
"System.InvalidOperationException: Collection was modified" occurs when querying data

### ISSUE THREAD

**Issue by mindcrash** [jonwagner/Insight.Database#393]
# Describe the bug

We are using async queries with custom mappers and rules. Every now and then the query blows up and the runtime throws the following exception and stack trace in the debug output:

```
System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at System.Linq.Enumerable.SelectListIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Boolean& found)
   at Insight.Database.DbSerializationRule.GetCustomSerializer(ClassPropInfo prop)
   at Insight.Database.DbSerializationRule.EvaluateRules(ClassPropInfo prop)
   at Insight.Database.ColumnMapping.MapColumn(Type type, IDataReader reader, Int32 column, IColumnMapper overrideMapping)
   at System.Linq.Enumerable.SelectIPartitionIterator`2.PreallocatingToArray(Int32 count)
   at System.Linq.Enumerable.SelectIPartitionIterator`2.ToArray()
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Insight.Database.ColumnMapping.MapColumns(Type type, IDataReader reader, Int32 startColumn, Nullable`1 columnCount, IColumnMapper overrideMapping)
   at Insight.Database.CodeGenerator.ClassDeserializerGenerator.MapColumns(Type type, IDataReader reader, Int32 startColumn, Int32 columnCount, IRecordStructure structure, Boolean allowBindChild)
   at Insight.Database.CodeGenerator.ClassDeserializerGenerator.DetectEndColumn(IDataReader reader, IRecordStructure structure, Int32 columnIndex, Type[] types, Int32 typeIndex)
   at Insight.Database.CodeGenerator.ClassDeserializerGenerator.CreateDeserializersForSubObjects(Type[] subTypes, IDataReader reader, IRecordStructure structure, Boolean allowBindChild)
   at Insight.Database.CodeGenerator.ClassDeserializerGenerator.CreateGraphDeserializer(Type[] subTypes, IDataReader reader, IRecordStructure structure, Boolean allowBindChild)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Insight.Database.CodeGenerator.DbReaderDeserializer.GetDeserializer(IDataReader reader, Type type, IRecordStructure structure, SchemaMappingType mappingType)
   at Insight.Database.CodeGenerator.DbReaderDeserializer.GetDeserializer[T](IDataReader reader, IRecordStructure structure)
   at Insight.Database.DBConnectionExtensions.AsyncReader`1.MoveNextAsync()
   at Insight.Database.DBConnectionExtensions.ToListAsync[T](IDataReader reader, IRecordReader`1 recordReader, CancellationToken cancellationToken, Boolean firstRecordOnly)
   at Insight.Database.Structure.SingleReader`1.ReadAsync(IDbCommand command, IDataReader reader, CancellationToken cancellationToken)
   at Insight.Database.DBConnectionExtensions.ExecuteAsyncAndAutoClose[T](IDbConnection connection, Object parameters, Func`2 getCommand, Boolean callGetReader, Func`3 translate, CommandBehavior commandBehavior, CancellationToken cancellationToken, Object outputParameters)
```

## Steps to reproduce

1. Connect to database
2. Run a async query with custom rules and type mapping a few times
3. Check the console and/or debugger

## Expected behavior

Query executes without exceptions

- Dotnet version: netcore2
- Database: Postgres
- Library version: 6.2.8

**Comment by jonwagner** [comment]
This isn’t quite enough information to reproduce the problem.

From the stack trace it does seem related to custom mapping rules. Can you share your configuration? Ideally a minimal set of rules that reproduces the problem.

On Mar 21, 2019, at 12:29 PM, mindcrash <notifications@github.com<mailto:notifications@github.com>> wrote:

Describe the bug

We are using async queries with custom mappers and rules. Every now and then the query blows up and the runtime throws the following exception and stack trace in the debug output:

System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at System.Linq.Enumerable.SelectListIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Boolean& found)
   at Insight.Database.DbSerializationRule.GetCustomSerializer(ClassPropInfo prop)
   at Insight.Database.DbSerializationRule.EvaluateRules(ClassPropInfo prop)
   at Insight.Database.ColumnMapping.MapColumn(Type type, IDataReader reader, Int32 column, IColumnMapper overrideMapping)
   at System.Linq.Enumerable.SelectIPartitionIterator`2.PreallocatingToArray(Int32 count)
   at System.Linq.Enumerable.SelectIPartitionIterator`2.ToArray()
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Insight.Database.ColumnMapping.MapColumns(Type type, IDataReader reader, Int32 startColumn, Nullable`1 columnCount, IColumnMapper overrideMapping)
   at Insight.Database.CodeGenerator.ClassDeserializerGenerator.MapColumns(Type type, IDataReader reader, Int32 startColumn, Int32 columnCount, IRecordStructure structure, Boolean allowBindChild)
   at Insight.Database.CodeGenerator.ClassDeserializerGenerator.DetectEndColumn(IDataReader reader, IRecordStructure structure, Int32 columnIndex, Type[] types, Int32 typeIndex)
   at Insight.Database.CodeGenerator.ClassDeserializerGenerator.CreateDeserializersForSubObjects(Type[] subTypes, IDataReader reader, IRecordStructure structure, Boolean allowBindChild)
   at Insight.Database.CodeGenerator.ClassDeserializerGenerator.CreateGraphDeserializer(Type[] subTypes, IDataReader reader, IRecordStructure structure, Boolean allowBindChild)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Insight.Database.CodeGenerator.DbReaderDeserializer.GetDeserializer(IDataReader reader, Type type, IRecordStructure structure, SchemaMappingType mappingType)
   at Insight.Database.CodeGenerator.DbReaderDeserializer.GetDeserializer[T](IDataReader reader, IRecordStructure structure)
   at Insight.Database.DBConnectionExtensions.AsyncReader`1.MoveNextAsync()
   at Insight.Database.DBConnectionExtensions.ToListAsync[T](IDataReader reader, IRecordReader`1 recordReader, CancellationToken cancellationToken, Boolean firstRecordOnly)
   at Insight.Database.Structure.SingleReader`1.ReadAsync(IDbCommand command, IDataReader reader, CancellationToken cancellationToken)
   at Insight.Database.DBConnectionExtensions.ExecuteAsyncAndAutoClose[T](IDbConnection connection, Object parameters, Func`2 getCommand, Boolean callGetReader, Func`3 translate, CommandBehavior commandBehavior, CancellationToken cancellationToken, Object outputParameters)


Steps to reproduce

  1.  Connect to database
  2.  Run a async query with custom rules and type mapping a few times
  3.  Check the console and/or debugger

Expected behavior

Query executes without exceptions

  *   Dotnet version: netcore2
  *   Database: Postgres
  *   Library version: 6.2.8

**Comment by mindcrash** [comment]
Hi Jon,

Thanks for the quick reply.

I think I have already found the culprit though. Could this be occuring due to DbSerializationRule.AddRule being hit with the same custom serialization rule before asynchronously running a query hitting that specific rule a couple of times?

**Comment by jonwagner** [comment]
Probably. Addrule should only be called once during your initialization so if you do it multiple times thats possible. Check that out. We can also put some code in to fix it if that’s the case.

On Mar 22, 2019, at 12:52 PM, mindcrash <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi Jon,

Thanks for the quick reply.

I think I have already found the culprit though. Could this be occuring due to DbSerializationRule.AddRule being hit with the same custom serialization rule before asynchronously running a query hitting that specific rule a couple of times?

**Comment by mindcrash** [comment]
We solved it by moving some stuff around and initializing it once.
