### ISSUE TITLE
NullReferenceException calling InsertAsync

### ISSUE THREAD

**Issue by elandev** [jonwagner/Insight.Database#495]
# Describe the bug
Get a `NullReferenceException `when calling `InsertAsync` with a stored procedure. See exception below.

When I use `ExecuteAsync `with the same stored procedure it works.

```
Object reference not set to an instance of an object.
   at Insight.Database.DbSerializationRule.EvaluateRules(ClassPropInfo prop)
   at Insight.Database.ColumnMapping.MapParameter(Type type, IDbCommand command, IDataParameter parameter)
   at System.Linq.Enumerable.SelectListIterator`2.ToList()
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Insight.Database.CodeGenerator.DbParameterGenerator.CreateClassInputParameterGenerator(IDbCommand command, Type type)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Insight.Database.DBCommandExtensions.AddParameters(IDbCommand cmd, Object parameters)
   at Insight.Database.DBConnectionExtensions.CreateCommand(IDbConnection connection, String sql, Object parameters, CommandType commandType, Nullable`1 commandTimeout, IDbTransaction transaction)
   at Insight.Database.DBConnectionExtensions.<>c__DisplayClass21_0`1.<InsertAsync>b__0(IDbConnection c)
   at Insight.Database.DBConnectionExtensions.<ExecuteAsyncAndAutoClose>d__36`1.MoveNext()
   at TestMySql.Program.<InsertData>d__7.MoveNext() in C:\Dev\src\Scratch\TestMySqlInsert\Program.cs:line 101
```

## Steps to reproduce
1. Load the attached project with Visual Studio 2022.
2. Set up MariaDB as the database (10.11.2-MariaDB).
3. Edit the server, database name and credentials for the connection string.
4. Restore Nuget packages and build the solution.
5. Run the project.

## Expected behavior
I expected the `InsertAsync `to work and return the auto-incremented ID.

- Dotnet version: 6.0
- Database: 10.11.2-MariaDB
- Library version: Insight 6.3.11
 
[TestMySqlInsert.zip](https://github.com/jonwagner/Insight.Database/files/11069710/TestMySqlInsert.zip)

**Comment by elandev** [comment]
This issue still exists. Is there an update on this?

**Comment by jonwagner** [comment]
Unfortunately, we can't accept project zip files as reproduction cases. Please paste sufficient code to reproduce here, or submit a PR with a failing test case.
